version: '3.8'

services:

  postgres:
    image: postgres:14
    container_name: employee_postgres
    environment:
      POSTGRES_DB: employees
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

  spark:
    build: ./spark
    container_name: employee_spark
    depends_on:
      - postgres
    volumes:
      - ./spark/jobs:/opt/spark/jobs
      - ./data:/opt/spark/data
    command: >
      /opt/spark/bin/spark-submit
      --master local[*]
      /opt/spark/jobs/employee_pipeline.py
